### ISSUE TITLE
StackOverflowError when retrieving a lock from WeakLazyStripes

### ISSUE THREAD

**Issue by adamretter** [evolvedbinary/fusiondb-server#9]
As reported to me:

"I’ve been using the Docker instance for two weeks now, quite successfully. However, please note the transcript below – the WeakLazyStripes part. This happened a number of days ago, but has not affected my ability to work with the Docker instance. In other words, it’s still running just fine."

```
20 Sep 2019 17:38:50,405 [main] INFO  (JettyStart.java [run]:286) - FusionDB Server has started, listening on:
20 Sep 2019 17:38:50,406 [main] INFO  (JettyStart.java [run]:288) -     http://172.17.0.2:4059/
20 Sep 2019 17:38:50,407 [main] INFO  (JettyStart.java [run]:288) -     https://172.17.0.2:5059/
20 Sep 2019 17:38:50,407 [main] INFO  (JettyStart.java [run]:291) - Configured contexts:
20 Sep 2019 17:38:50,407 [main] INFO  (JettyStart.java [run]:297) -     /
20 Sep 2019 17:38:50,408 [main] INFO  (JettyStart.java [run]:312) - '/iprange'
20 Sep 2019 17:38:50,408 [main] INFO  (JettyStart.java [run]:297) -     /exist
20 Sep 2019 17:38:50,409 [main] INFO  (JettyStart.java [run]:312) - '/exist/iprange'
20 Sep 2019 17:38:50,409 [main] INFO  (JettyStart.java [run]:318) - -----------------------------------------------------
20 Sep 2019 17:39:20,410 [qtp502066023-80] WARN  (Descriptor.java [<init>]:116) - Giving up unable to read descriptor.xml file from classloader in package org.exist.http, eXist-db Core, version 1.0
20 Sep 2019 17:50:52,849 [qtp502066023-77] INFO  (TemporaryFileManager.java [<init>]:109) - Temporary folder is: /tmp/exist-db-temp-file-manager-5119084716874131087
21 Sep 2019 22:26:12,235 [qtp502066023-229] WARN  (TransactionManager.java [close]:528) - Transaction was not committed or aborted, auto aborting!
21 Sep 2019 22:26:12,266 [qtp502066023-229] ERROR (EXistServlet.java [doGet]:285) - null

java.lang.StackOverflowError: null
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:177) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
        at org.exist.util.WeakLazyStripes.get(WeakLazyStripes.java:214) ~[fusiondb-server.uber.jar:1.0.0-ALPHA2]
```

**Comment by adamretter** [comment]
I fixed this upstream in eXist-db on 11th Nov 2019 - https://github.com/eXist-db/exist/pull/3064
